//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZDInsaatMvc.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Id { get; set; }
        public string AdiSoyadi { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public string EkleyenKisi { get; set; }
        public Nullable<System.DateTime> DegistirilmeTarihi { get; set; }
        public string DegistirenKisi { get; set; }
        public string Resim { get; set; }
        public string Role { get; set; }
        public string OturumId { get; set; }
    }
}
