//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZDInsaatMvc.DbService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NZDInsaatDbEntities : DbContext
    {
        public NZDInsaatDbEntities()
            : base("name=NZDInsaatDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CozumOrtaklari> CozumOrtaklari { get; set; }
        public virtual DbSet<CozumOrtaklariAnasayfa> CozumOrtaklariAnasayfa { get; set; }
        public virtual DbSet<IsOrtaklari> IsOrtaklari { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Projeler> Projeler { get; set; }
    }
}
